---
openapi: "3.1.0"
info:
  title: "Tornado RESTful API"
  description: ""
  version: "1.0"
servers:
  - url: http://localhost:8080
    description: "Local server"
paths:
  /api/v1/projects:
    get:
      tags:
      - "Projects"
      responses:
        "200":
          description: "All projects"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/com.github.mantasjasikenas.model.PostProjectDto"
    post:
      tags:
      - "Projects"
      responses:
        "201":
          description: "Project created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/com.github.mantasjasikenas.model.ProjectDto"
        "400":
          description: "Bad request"
          content:
            application/json:
              schema:
                type: "string"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/com.github.mantasjasikenas.model.PostProjectDto"
  /api/v1/projects/{id}:
    get:
      tags:
      - "Projects"
      responses:
        "200":
          description: "Project by id"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/com.github.mantasjasikenas.model.ProjectDto"
        "400":
          description: "Bad request"
          content:
            application/json:
              schema:
                type: "string"
        "404":
          description: "Not found"
          content:
            application/json:
              schema:
                type: "string"
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
    put:
      tags:
      - "Projects"
      responses:
        "200":
          description: "Project updated"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/com.github.mantasjasikenas.model.ProjectDto"
        "400":
          description: "Bad request"
          content:
            application/json:
              schema:
                type: "string"
        "404":
          description: "Not found"
          content:
            application/json:
              schema:
                type: "string"
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/com.github.mantasjasikenas.model.UpdateProjectDto"
    delete:
      tags:
      - "Projects"
      responses:
        "204":
          description: "Project deleted"
          content:
            application/json:
              schema:
                type: "string"
        "400":
          description: "Bad request"
          content:
            application/json:
              schema:
                type: "string"
        "404":
          description: "Not found"
          content:
            application/json:
              schema:
                type: "string"
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
  /api/v1/sections/{sectionId}/tasks:
    post:
      tags:
      - "Tasks"
      responses:
        "201":
          description: "Task created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/com.github.mantasjasikenas.model.TaskDto"
        "400":
          description: "Bad request"
          content:
            application/json:
              schema:
                type: "string"
      parameters:
      - name: "sectionId"
        in: "path"
        required: true
        schema:
          type: "string"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/com.github.mantasjasikenas.model.PostTaskDto"
  /api/v1/projects/{projectId}/sections/{sectionId}/tasks:
    get:
      tags:
      - "Tasks"
      responses:
        "200":
          description: "All tasks"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/com.github.mantasjasikenas.model.TaskDto"
      parameters:
      - name: "projectId"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "sectionId"
        in: "path"
        required: true
        schema:
          type: "string"
  /api/v1/tasks:
    get:
      tags:
      - "Tasks"
      responses:
        "200":
          description: "All tasks"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/com.github.mantasjasikenas.model.TaskDto"
  /api/v1/tasks/{id}:
    get:
      tags:
      - "Tasks"
      responses:
        "200":
          description: "Task by id"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/com.github.mantasjasikenas.model.TaskDto"
        "400":
          description: "Bad request"
          content:
            application/json:
              schema:
                type: "string"
        "404":
          description: "Not found"
          content:
            application/json:
              schema:
                type: "string"
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
    put:
      tags:
      - "Tasks"
      responses:
        "200":
          description: "Task updated"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/com.github.mantasjasikenas.model.TaskDto"
        "400":
          description: "Bad request"
          content:
            application/json:
              schema:
                type: "string"
        "404":
          description: "Not found"
          content:
            application/json:
              schema:
                type: "string"
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/com.github.mantasjasikenas.model.UpdateTaskDto"
    delete:
      tags:
      - "Tasks"
      responses:
        "200":
          description: "Task removed"
          content:
            application/json:
              schema:
                type: "string"
        "404":
          description: "Not found"
          content:
            application/json:
              schema:
                type: "string"
        "400":
          description: "Bad request"
          content:
            application/json:
              schema:
                type: "string"
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
  /api/v1/projects/{projectId}/sections:
    post:
      tags:
      - "Sections"
      responses:
        "201":
          description: "Section created"
          content:
            application/json:
              schema:
                type: "integer"
        "400":
          description: "Bad request"
          content:
            application/json:
              schema:
                type: "string"
      parameters:
      - name: "projectId"
        in: "path"
        required: true
        schema:
          type: "string"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/com.github.mantasjasikenas.model.PostSectionDto"
  /api/v1/sections:
    get:
      tags:
      - "Sections"
      responses:
        "200":
          description: "All sections"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/com.github.mantasjasikenas.model.PostSectionDto"
  /api/v1/sections/{id}:
    get:
      tags:
      - "Sections"
      responses:
        "200":
          description: "Section by id"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/com.github.mantasjasikenas.model.PostSectionDto"
        "400":
          description: "Bad request"
          content:
            application/json:
              schema:
                type: "string"
        "404":
          description: "Not found"
          content:
            application/json:
              schema:
                type: "string"
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
    delete:
      tags:
      - "Sections"
      responses:
        "204":
          description: "Section deleted"
          content:
            application/json:
              schema:
                type: "string"
        "400":
          description: "Bad request"
          content:
            application/json:
              schema:
                type: "string"
        "404":
          description: "Not found"
          content:
            application/json:
              schema:
                type: "string"
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
  /api/v1/sections/{sectionId}:
    put:
      tags:
      - "Sections"
      responses:
        "200":
          description: "Section updated"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/com.github.mantasjasikenas.model.SectionDto"
        "400":
          description: "Bad request"
          content:
            application/json:
              schema:
                type: "string"
        "404":
          description: "Not found"
          content:
            application/json:
              schema:
                type: "string"
      parameters:
      - name: "sectionId"
        in: "path"
        required: true
        schema:
          type: "string"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/com.github.mantasjasikenas.model.UpdateSectionDto"
components:
  schemas:
    com.github.mantasjasikenas.model.PostProjectDto:
      type: "object"
      properties:
        createdBy:
          type: "string"
          description: "Project creator"
        description:
          type: "string"
          description: "Project description"
        name:
          type: "string"
          description: "Project name"
      required:
      - "name"
      - "description"
      - "createdBy"
    com.github.mantasjasikenas.model.PostSectionDto:
      type: "object"
      properties:
        createdBy:
          type: "string"
          description: "Section creator"
        name:
          type: "string"
          description: "Section name"
      required:
      - "name"
      - "createdBy"
    com.github.mantasjasikenas.model.PostTaskDto:
      type: "object"
      properties:
        createdBy:
          type: "string"
          description: "Task creator"
        description:
          type: "string"
          description: "Task description"
        dueDate:
          type: "string"
          description: "Task due date"
        isCompleted:
          type: "boolean"
          description: "Task completion status"
        name:
          type: "string"
          description: "Task name"
        priority:
          type: "string"
          enum:
          - "Low"
          - "Medium"
          - "High"
          - "Vital"
          description: "Task priority"
      required:
      - "name"
      - "description"
      - "priority"
      - "isCompleted"
      - "createdBy"
    com.github.mantasjasikenas.model.ProjectDto:
      type: "object"
      properties:
        createdAt:
          type: "string"
          description: "Project creation date"
        createdBy:
          type: "string"
          description: "Project creator"
        description:
          type: "string"
          description: "Project description"
        id:
          type: "integer"
          description: "Project id"
        name:
          type: "string"
          description: "Project name"
      required:
      - "id"
      - "name"
      - "description"
      - "createdAt"
      - "createdBy"
    com.github.mantasjasikenas.model.SectionDto:
      type: "object"
      properties:
        createdAt:
          type: "string"
          description: "Section creation date"
        createdBy:
          type: "string"
          description: "Section creator"
        id:
          type: "integer"
          description: "Section id"
        name:
          type: "string"
          description: "Section name"
        projectId:
          type: "integer"
          description: "Project id"
      required:
      - "id"
      - "projectId"
      - "name"
      - "createdBy"
      - "createdAt"
    com.github.mantasjasikenas.model.TaskDto:
      type: "object"
      properties:
        createdAt:
          type: "string"
          description: "Task creation date"
        createdBy:
          type: "string"
          description: "Task creator"
        description:
          type: "string"
          description: "Task description"
        dueDate:
          type: "string"
          description: "Task due date"
        id:
          type: "integer"
          description: "Task id"
        isCompleted:
          type: "boolean"
          description: "Task completion status"
        name:
          type: "string"
          description: "Task name"
        priority:
          type: "string"
          enum:
          - "Low"
          - "Medium"
          - "High"
          - "Vital"
          description: "Task priority"
        sectionId:
          type: "integer"
          description: "Section id"
      required:
      - "id"
      - "sectionId"
      - "name"
      - "description"
      - "priority"
      - "isCompleted"
      - "createdBy"
      - "createdAt"
    com.github.mantasjasikenas.model.UpdateProjectDto:
      type: "object"
      properties:
        description:
          type: "string"
          description: "Project description"
        name:
          type: "string"
          description: "Project name"
    com.github.mantasjasikenas.model.UpdateSectionDto:
      type: "object"
      properties:
        name:
          type: "string"
          description: "Section name"
    com.github.mantasjasikenas.model.UpdateTaskDto:
      type: "object"
      properties:
        description:
          type: "string"
          description: "Task description"
        dueDate:
          type: "string"
          description: "Task due date"
        isCompleted:
          type: "boolean"
          description: "Task completion status"
        name:
          type: "string"
          description: "Task name"
        priority:
          type: "string"
          enum:
          - "Low"
          - "Medium"
          - "High"
          - "Vital"
          description: "Task priority"
        sectionId:
          type: "integer"
          description: "Task creator"
