services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./src/main/kotlin/com/github/mantasjasikenas/db/dumps/init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    #    volumes:
    #      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
#volumes:
#  pgdata:
